### ISSUE TITLE
How to smoothly interpolate between CPPN parameterizations?

### ISSUE THREAD

**Issue by thoppe** [tensorflow/lucid#102]
This is less of an issue and more of a discussion, so please tag appropriately. I took the Lucid library and set some of the channel renderings to music:

video: https://www.youtube.com/watch?v=qPi5UPAlwl8
repo: https://github.com/thoppe/DeepMDMA

I'm really pleased with the result (and kudos for such an awesome library that's easy to hack on!). My question involves the transition between the parameterizations. In my video (and in the last video of the this [notebook](https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/differentiable-parameterizations/xy2rgb.ipynb) especially), the CPPN blurs out between each image. This happens even if you train a hundred different models all on the same channel, due to the different local minima found from the random initializations. 

To mitigate this somewhat, I started with a source parameterization P(t=0), slowly moved the optimization, and retrained _starting from the prior timestep initialization_. This definitely helps, but it takes forever to train the model iteratively like this! Is there a way to keep the CPPN in a visual appealing part of the space when interpolating?

**Comment by ludwigschubert** [comment]
If you have a question about Lucid’s behavior and want to discuss it with other users, also consider the  `#proj-lucid` channel on the [Distill Community Slack Workspace](https://distillpub.slack.com) which you may [join here](https://join.slack.com/t/distillpub/shared_invite/enQtMzg1NzU3MzEzMTg3LWJkNmQ4Y2JlNjJkNDlhYTU2ZmQxMGFkM2NiMTI2NGVjNzJkOTdjNTFiOGZmNDBjNTEzZGUwM2U0Mzg4NDAyN2E).

Lucid is alpha-status research code, and we appreciate your understanding that this can sometimes mean we will not have the resources to resolve your specific issue—even if it may be an entirely reasonable request in a more mature codebase. Thank you! 🤗
