### ISSUE TITLE
Style transfer for videos

### ISSUE THREAD

**Issue by martync** [tensorflow/lucid#105]
Hi, 

Your approach of style transfer is interesting and gives very good results imo. My knowledge of neural networks and style transfer is limited and I wanted an advice about the possibilities to add Deepflow to this algorithm to be able to style-transfer videos. 
Comparing the code of https://github.com/cysmith/neural-style-tf and yours, the logic looks totally different.
Let me know if you think frame-interpolation is quite-easily faisible and I'll dig it.

Thanks

**Comment by colah** [comment]
Hi! I expect that our approach to style transfer could work well for video, but that it would take a bit of effort to get right.

My intuition would be to try to achieve frame alignment by choosing the right parameterization. A first thing you could try is something along the lines of what we did in [aligned interpolation](https://distill.pub/2018/differentiable-parameterizations/#section-aligned-interpolation). I suspect you could do much better by crafting a custom parameterization based on an optical flow.

**Comment by ludwigschubert** [comment]
Closing for now, but feel free to reopen if you try implementing this and have further questions!

**Comment by martync** [comment]
Thanks for your reply and explanations. I'll do my best and let you know if I get good results.

**Comment by martync** [comment]
I've been working several hours on this and I must admit that this is too tricky for me. Going back to a lib that already support optical flow and try to tweak it a bit to get rid of several artefacts.

**Comment by merri-ment** [comment]
Hi @ludwigschubert / @colah 

Do you know if anyone achieved Shared Parameterization across multiple content frames by adjusting the style-transfer-2d.ipynb example? I had a look at the Aligned Interpolation.ipynb example for a few hours, without making much headway.
