### ISSUE TITLE
displaying image result outside of jupyter

### ISSUE THREAD

**Issue by crasse2** [tensorflow/lucid#108]
Hi !

sorry if my question is quite silly, I'm quite new to python and image handling, However I've been messing around with Deep Dream and Neural-Transfer previously and I recently found Lucid, and I'm completly amazed by what it does, so thanks for sharing your work and knowledge !! 

however I tried to play with the code directly on python (outside of jupyter) and I've come across a problem :
the `render.render_vis` command output a list of values and then when I convert it to an array with numpy, I get a 5 dimensional array (which is not convertible into an image in this state) but I see that in the notebook file you provide, this array is displayed as an image, so basicly how can I manually convert it to an image directly in a .py file ?
(in an other way, how can I display or save the result of `render.render_vis` as an image, using PIL, pyplot or numpy for example ?)

another subplot :
i'm working on python 2.7 and to get it working on it I modified the vision_base.py file on line 75 to :  

```
class Model(object):
  __metaclass__ = ModelPropertiesMetaClass
```

before building and installing it, as the metaclass syntax changed on python 3, a small modification but if it can help for some python 2 users :)

**Comment by ludwigschubert** [comment]
The result of `render_vis` should be a (Python) array of the optimization result at each step specified in `threshold`s. If you didn't specify them, you'll get a list with just one entry. That entry is a numpy array of shape Batch x Width x Height x Channels. If your batch dimension is just 1—which it is by default—then you can simply index into that numpy array and use the `save` helper to save it as a file which you can then view outside of python.

Writing this from memory, so it may have syntax issues:
```
from lucid.optvis.render import render_vis
from lucid.misc.io import save

results_at_thresholds = render_vis(…)
last_result = results_at_thresholds[-1] # gets result at last threshhold
image = last_result[0] # gets first image from batch
save(image, "path/to/result.jpg")
```

Closing in the hopes this helps, but let me know if you need more assistance!

Re subplot: unfortunate timing; this will be fixed today.

**Comment by crasse2** [comment]
perfect !! thanks for the assistance, that works !

I think I didn't read carefully enough all the documents you provided about your method, I will re read them to understand Lucid better ;)
