### ISSUE TITLE
questions about the style-transfer methods

### ISSUE THREAD

**Issue by crasse2** [tensorflow/lucid#109]
Hi !
I've been playing a lot with Lucid the past 2 days, and especially with the style-transfer method, and It gives fantastic results !! 

However I've come across some observations or questions :

- ### question about constancy and consistency :
I saw that, while executing the style transfer method on the same content image, with the same style image and the same transform settings give different results each times. I tried without the tf.random_crop, thinking randomness came from that, but still different results each time.
So I'm wondering, does the process initiate by generating a random noise at the start of the process, as does the older version of Neural-Style by Justin Johnson, which can be replaced by an image as an init-image parameters to get constancy in results ? (which can be useful to build an stepped upscaling transfer method, initiating the transfer process on an image and not on random-noise)

- ### question about using other models :
I've also tried transfer with another model, the InceptionV4_slim, and the transfer process itself works, but the result is close to the content image, with really low Style Loss and Content Loss values ( InceptionV1 producing good results with Loss values between 300 and 600, and with the V4_slim I get Loss values between only 1 and 12, but similar process time, and GPU usage).
I tried lots of different layers combination, according to the layer graph you provided in the notebooks, but each time I got really small Loss values, and accordingly to those values, a result image close to the original content one.
Do you have an idea of which parameters or settings I should modify or test to increase or decrease Losses value on other models than V1 ?

**Comment by colah** [comment]
> ... I tried without the tf.random_crop, thinking randomness came from that, but still different results each time. So I'm wondering, does the process initiate by generating a random noise at the start of the process, as does the older version of Neural-Style by Justin Johnson, which can be replaced by an image as an init-image parameters to get constancy in results ?

Yes, there are multiple sources of randomness. tf.random_crop is one, but is important. You should probably fix the random seed for it instead. There is also initial random noise.

> Do you have an idea of which parameters or settings I should modify or test to increase or decrease Losses value on other models than V1 ?

We haven't tuned style transfer for any other models.
