### ISSUE TITLE
Are these visuals enhanced??

### ISSUE THREAD

**Issue by bluesky314** [tensorflow/lucid#112]
I have a lot of interest in the contents of this library however the neutron visualisations seem vastly different and more colourful then anything I have seen before. Eg.) https://blog.keras.io/how-convolutional-neural-networks-see-the-world.html shows the same but Lucid's are sooo colourful and bright. Which is accurate and why are Lucid's like this. What method are they using to visualise the activations?

**Comment by colah** [comment]
Hello!

No, they aren't enhanced. That's just the result of the visualizations.

I would guess the ones in the Keras post would come out the same if they ran them for long enough or added some tricks to their algorithm. If you do feature visualization (or as they call it, activation maximization) naively, it quickly fills in edges and very slowly gets other things. You can fix this by running longer, using a conditioner, or using a better parameterization of your image. Using more sophisticated transformation robustness also helps a lot.

You can read more details in the [Feature Visualization post](https://distill.pub/2017/feature-visualization/).
