### ISSUE TITLE
Errors when using official Resnet model

### ISSUE THREAD

**Issue by Arturus** [tensorflow/lucid#124]
Hi!
I can't get Lucid to work with model trained on "official Resnet" code: https://github.com/tensorflow/models/tree/master/official/resnet

### Steps to reproduce
1. Official pretrained model is unusable because of harcoded batch dimension (64). I slightly tweaked model export code to get free batch dimension + some preprocessing tweaks, and trained Resnet-50 v1 model on Imagenet.
2. Export frozen graph from SavedModel: ``!python ~/miniconda3/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py --input_saved_model_dir exported_model/1542646825 --output_node_names softmax_tensor --output_graph /tmp/resnet50.pb.zoo``
3. Load frozen graph into custom Lucid model:
```python
from lucid.modelzoo.vision_base import Model
class MyResnet(Model):
    image_shape = [224, 224, 3]
    model_path  = '/tmp/resnet50.pb.zoo'
    labels_path = 'gs://modelzoo/labels/ImageNet_standard.txt'
    image_value_range = (-117, 255-117)
    input_name = 'input_tensor'
model = MyResnet()
model.load_graphdef()
```
4. Try to render response from any channel of last Resnet block:
```python
obj = objectives.channel("resnet_model/block_layer4", 42)
param_f = lambda: param.image(256, fft=True, decorrelate=True, batch=1)
_ = render.render_vis(model, obj, param_f=param_f)
```
5. **Fail!**
```
InvalidArgumentError: Inputs to operation gradients/import/resnet_model/Relu_48_grad/Select of type Select must have the same size and shape.  Input 0: [1,2048,9,9] != input 1: [1,2048,7,7]
	 [[{{node gradients/import/resnet_model/Relu_48_grad/Select}} = Select[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/import/resnet_model/Relu_48_grad/Less, gradients/import/resnet_model/Relu_42_grad/Select-1-TransposeNHWCToNCHW-LayoutOptimizer, gradients/import/resnet_model/Relu_48_grad/Select-2-TransposeNHWCToNCHW-LayoutOptimizer)]]
	 [[{{node Mean/_45}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3442_Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```
This is strange error because model has fixed shape for all dimensions except batch. Tensor with shape [1,2048,9,9] just should not exist.
Size of 'bad dimension' (9 in this case) depends on rendered image size. If I use larger image size (512), bad dimension goes to 12 or 13.
Lucid don't accept NCHW, I tried to а) train model with NCHW and export results to NHWC, and b) directly train model in NHWC - same results.

I made a gist with complete code sample and model sanity check: https://gist.github.com/Arturus/c93052e951d5bc04fcd79c714d6175b6

Can you help me?

**Comment by Arturus** [comment]
Same experience with Resnet50 model imported from Tensorpack library https://github.com/tensorpack/tensorpack/tree/master/examples/ResNet
```
InvalidArgumentError: Inputs to operation gradients/import/resnet50/group3/block2/Relu_grad/Select of type Select must have the same size and shape.  Input 0: [1,9,9,2048] != input 1: [1,7,7,2048]
	 [[{{node gradients/import/resnet50/group3/block2/Relu_grad/Select}} = Select[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/import/resnet50/group3/block2/Relu_grad/Less, gradients/import/resnet50/group3/block0/Relu_grad/zeros_like, gradients/strided_slice_13_grad/StridedSliceGrad)]]
```
It seems like Lucid only loves tf-slim based Resnet models. I imported custom tf-slim model without any problems.

**Comment by colah** [comment]
Hi Arturus,

It looks to me like your model hard codes the shapes of layers somewhere. This can easily happen, for instance, if you have a fully connected layer. This means that it's inflexible about the shape of the image you optimize, and will error out if you give the wrong input shape.

It looks like you're optimizing an image that's a different shape from the input. For many models this is fine -- and very convenient -- but it may be problematic for your model.

```py
class MyResnet(Model):
    image_shape = [224, 224, 3]   #   <========== model input shape is 224x224 ?
    model_path  = '/tmp/resnet50.pb.zoo'
    labels_path = 'gs://modelzoo/labels/ImageNet_standard.txt'
    image_value_range = (-117, 255-117)
    input_name = 'input_tensor'
```

```py 
obj = objectives.channel("resnet_model/block_layer4", 42)
param_f = lambda: param.image(256, fft=True, decorrelate=True, batch=1) # <==== model may not be able to support optimizing a 256x256 image.
_ = render.render_vis(model, obj, param_f=param_f)
```

**Comment by Arturus** [comment]
> It looks like you're optimizing an image that's a different shape from the input. For many models this is fine -- and very convenient -- but it may be problematic for your model.

Thank you for answer, but unfortunately model fails even if I optimize for 'valid' image size:
```python
obj = objectives.channel("resnet_model/add_15", 42)
param_f = lambda: param.image(224, fft=True, decorrelate=True, batch=1) 
```
```
InvalidArgumentError: Conv2DCustomBackpropInput: Size of out_backprop doesn't match computed: actual = 9, computed = 7 spatial_dim: 1 input: 7 filter: 1 output: 9 stride: 1 dilation: 1
	 [[{{node gradients/import/resnet_model/conv2d_52/Conv2D_grad/Conv2DBackpropInput}} = Conv2DBackpropInput[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ConstantFolding/gradients/import/resnet_model/conv2d_52/Conv2D_grad/ShapeN-matshapes-0, import/resnet_model/conv2d_52/kernel, gradients/import/resnet_model/batch_normalization_52/FusedBatchNorm_grad/FusedBatchNormGrad)]]
```
Additionally I tried to declare different size (235x235) in Lucid model description (MyResnet class) and run inference for that size. It works, so model can handle non-standard input sizes.

Today I trained another tf-slim based ResNet model - again, it works with Lucid. Any other Resnet don't work.

PS
Why I see ``gradients/import/resnet_model/conv2d_52/Conv2D_grad/Conv2DBackpropInput`` in a *FROZEN* model? Why optimizer tries to run backprop for frozen, constant layers? May be freeze_graph.py did not freeze model completely?

**Comment by colah** [comment]
@Arturus - Do you know what image size your model was trained on? If your model is inflexible, it needs to be give the correct input size in both places.

> Why I see gradients/import/resnet_model/conv2d_52/Conv2D_grad/Conv2DBackpropInput in a FROZEN model? Why optimizer runs backprop for frozen, constant layers? May be freeze_graph.py did not freeze model completely?

In order to create your visualizations, Lucid needs to backprop through your model. You can read more about this in [Feature Visualization](https://distill.pub/2017/feature-visualization/).

**Comment by Arturus** [comment]
@colah This is not my model, this is Google official ResNet.
I did'nt changed anything except slightly different preprocessing of RGB values before they enter the network. Image size is standard for Resnet-50: 224 px.
If you want, I can setup Colab notebook where you can play with code.

> In order to create your visualizations, Lucid needs to backprop through your model.

Yep, I know, but frozen model should be just a static function, there is nothing to optimize. Stacktrace looks like optimizer is doing something inside the model, that's why I asked a question.

**Comment by hegman12** [comment]
Can you try setting transform to empty list []  and try?

**Comment by Arturus** [comment]
> Can you try setting transform to empty list [] and try?

Could you please clarify what transform do you mean?

**Comment by Arturus** [comment]
> Can you try setting transform to empty list [] and try?

Yes, it works, but only for standard image size 224x224.
But same model accepts image of any size for inference and works almost correctly (predictions are slightly off, that's expected for different image size, but it don't throws errors). 
What is wrong in model structure for Lucid? What should be changed?

**Comment by colah** [comment]
@hegman12 - Thanks for catching that. We should have a standard debugging question list...

@Arturus - Something about how your model is written hard codes input size.

You can still visualize your model with this, it's just a bit less convenient. Try setting `transforms=[transform.jitter(4)]` and your image size to `227` (224+3).

> But same model accepts image of any size for inference and works almost correctly (predictions are slightly off, that's expected for different image size, but it don't throws errors).

The model likely rescales them to 224x224 for inference.

**Comment by Arturus** [comment]
> Something about how your model is written hard codes input size.

> The model likely rescales them to 224x224 for inference.

This is a first operations of model graph:
```python
inp = tf.placeholder(tf.float32, [224,224,3], 'Input')
model.import_graph(t_input=inp, scope='test')
tf.get_default_graph().get_operations()
```
```
<tf.Operation 'Input' type=Placeholder>,
 <tf.Operation 'ExpandDims/dim' type=Const>,
 <tf.Operation 'ExpandDims' type=ExpandDims>,
 <tf.Operation 'PlaceholderWithDefault' type=PlaceholderWithDefault>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add/x' type=Const>,
 <tf.Operation 'add' type=Add>,
 <tf.Operation 'test/input_tensor' type=Placeholder>,
 <tf.Operation 'test/resnet_model/Pad/paddings' type=Const>,
 <tf.Operation 'test/resnet_model/Pad' type=Pad>,
 <tf.Operation 'test/resnet_model/conv2d/kernel' type=Const>,
 <tf.Operation 'test/resnet_model/conv2d/kernel/read' type=Identity>,
 <tf.Operation 'test/resnet_model/conv2d/Conv2D' type=Conv2D>,
 <tf.Operation 'test/resnet_model/initial_conv' type=Identity>
```
I don't see any resize operation here and don't see any resize in Python code.
The first 8 operations without `test` prefix (Placeholder, ExpandDims, Mul, Add, etc) are standard Lucid input preprocessing.
After preprocessing, the first Resnet convolutional layer begins.

To confirm that model does not scale the input, I fed images of different size to the input and printed output shape of last Resnet layer (just before the final AvgPool). As expected, output size grows with an image size. So the model don't have hardcoded size or rescale.
```
Input shape:(224, 224, 3), Last block shape:(1, 7, 7, 2048)
Input shape:(288, 288, 3), Last block shape:(1, 9, 9, 2048)
Input shape:(352, 352, 3), Last block shape:(1, 11, 11, 2048)
```
I set up Colab notebook, you can see live code here: https://colab.research.google.com/drive/1P8kxJkJjBdmfLGfXnhrlKDF0ScuUwg5l#scrollTo=t2SJM0jFJCBN

Sorry for intrusiveness, but I really want to understand what's going on.

**Comment by Arturus** [comment]
I resolved the problem.
Model must be exported without static shapes for image width and height. Static shapes don't do any harm for inference, model still works with input of any size. But they seems to be harmful for optimizer.
Still don't know why tf-slim model works perfectly with static shapes, but any other models are not. This is a dark Tensorflow magic :scream:

Input placeholder for Lucid-compatible model should have shape `[None, None, None, 3]`. Last Resnet layer will have shape `(1, ?, ?, 2048)` in this case.

BTW, what is a role of `image_shape` field in Model class? It can be set to any size, including empty shape [None, None, 3], visualization don't depends on its value.

**Comment by colah** [comment]
Woah, thanks you for digging into that @Arturus!

(It makes me wonder if we could automatically strip static shape info out of graphdefs before importing them?)

> BTW, what is a role of image_shape field in Model class? It can be set to any size, including empty shape [None, None, 3], visualization don't depends on its value.

For basic visualizations, it has no effect. However, there are many more sophisticated visualizations 
 -- for example, caricatures (#121) -- where we need to know the size of image the model takes.

**Comment by hegman12** [comment]
> Model must be exported without static shapes for image width and height.

Yes. Here is the architecture of lucid. I will get to the reason why it requires height,width to be none in a second.

[Architecture of Lucid](https://github.com/hegman12/Deep-learnig-with-tensorflow/blob/master/Lucid%20-%20library%20experiments/Architecture_of_lucid.jpeg)
     

When you specify the shape of image in param, `param_f = lambda: param.image(224, fft=True, decorrelate=True, batch=1) `, it is the shape of numpy image you are specifying(refer the above link). But before it actually fed to ResNet(or any other architectures you use), it will pass through _Transform_.
Here is the default transform setup in Lucid.
```
standard_transforms = [
    pad(12, mode="constant", constant_value=.5),
    jitter(8),
    random_scale([1 + (i - 5) / 50. for i in range(11)]),
    random_rotate(list(range(-10, 11)) + 5 * [0]),
    jitter(4),
]
```
As you can see, even if you specify size as 224, when it passes through transform layer, it will be converted to random shape. Then it is fed to model. If you have hard coded image shape in model architecture, this will fail. That is why i suggested you to set `transform` to empty list and use standard model input shape. In this way, you will effectively skip the transform step.

> Static shapes don't do any harm for inference, model still works with input of any size

If you have hard coded input shape(i.e static) in model and try to pass tensor with different shape , it will fail!

> Still don't know why tf-slim model works perfectly with static shapes, but any other model don't

There are models trained in caffe that can be visualized in lucid. So, i imagine it is not specific to tf.slim or other libraries. @colah or @ludwigschubert can confirm.

**Comment by colah** [comment]
@hegman12 - Nice diagram! :)

(I probably wouldn't have the NumPy Image step. We're really just using it to initialize TensorFlow variables, and depending on the parameterization they may not correspond to a "image." For example, often they represent the initial magnitudes of different frequencies.)

> There are models trained in caffe that can be visualized in lucid. So, i imagine it is not specific to tf.slim or other libraries. @colah or @ludwigschubert can confirm.

Yes. As long as the model isn't baking in its shape when it exports, we're fine.

I'm pretty sure they place they're getting baked in is convolution ops allowing users to hard code shapes for slightly faster inference.

**Comment by Arturus** [comment]
@hegman12 thanks for the explanation!
> If you have hard coded input shape(i.e static) in model and try to pass tensor with different shape , it will fail!

Not always. Tf-slim model has hardcoded static shape (you can look to the shapes of Resnet50 from Lucid model zoo) and don't fails. Inference don't fails for any model despite of different shape. You can see that in my colab notebook.

@colah
>  As long as the model isn't baking in shapes when it exports, we're fine. tf-slim / cafe / etc models work because they don't do this.

Cafe mode is just a bunch of weights from TF point of view, it can't define or not define any shape. Shapes are defined in a graph creation code which translates to TF operations. And tf-slim model HAS baked shapes, because they were defined in a python code.
It seems that some shapes are equal, but some are more equal than others )

Anyway, thank you people for help, I think we can close this ticket?

**Comment by hegman12** [comment]
> Not always. Tf-slim model has hardcoded static shape (you can look to the shapes of Resnet50 from Lucid model zoo) and don't fails. 


Thanks :) haven't realized it has static shape! will check it out.

> For example, often they represent the initial magnitudes of different frequencies.

agreed, thats why i had parameter image(i should actually use the word tensor, not image) and optimization 'image'.

@colah Thanks! I will delete that section, i will leave above image as it is. If i remove here, it may confuse the readers what your comment is referring to.
