### ISSUE TITLE
Support for 3D inputs 

### ISSUE THREAD

**Issue by koriavinash1** [tensorflow/lucid#127]
How to visualize of feature maps obtained from 3D CNN's using lucid api's ?

**Comment by ludwigschubert** [comment]
Hey @koriavinash1, we do not have support for 3D inputs built in. Support would consist of a 3D parameterization and robustness transforms.

You could look into `lucid.optvis.param` for how we construct parameterizations and build your own for the 3D input your model requires. Unfortunately we don't yet have any guides for this. The hard part would likely not just be the parameterization, but finding robustness transformations that work iwell n 3D… future research! Please let us know if you implement feature visualization in 3D!
