### ISSUE TITLE
Support for Audio (1D Conv) Feature visualization.

### ISSUE THREAD

**Issue by BadrYoubiIdrissi** [tensorflow/lucid#128]
I am working on Audio feature visualization by trying to apply already existing tools and research on vision. Lucid seems general enough to be used for Deep Neural Networks in Audio. I haven't read through all the code but I feel like the library could be more of a tool for visualization in the input space for deep neural networks. What do you think?

**Comment by ludwigschubert** [comment]
Hey @BadrYoubiIdrissi sorry for missing this until you closed the issue!

The concepts behind lucid are definitely general enough; we've done some audio experiments ourselves. The place to start would be to look at `lucid.optvis.param` and add an `audio` module. `lucid.optvis.transform` could become a package with a `spatial` and a `audio` module.

I'm afraid we won't be using this code for audio soon, but you'd be welcome to contribute and I'd happily review any proposals!
