### ISSUE TITLE
Feature visualization for semantic segmentation networks

### ISSUE THREAD

**Issue by koriavinash1** [tensorflow/lucid#133]
Are there any tutorials or example feature maps for semantic level segmentation networks?

**Comment by colah** [comment]
Unfortunately, there are not.

**Comment by ludwigschubert** [comment]
(Yet! Growth-mindset!)

@koriavinash1 if you continue on that line of research, we'd love to hear back if you get a result. Maybe your work can become the basis for such a tutorial notebook. :-)
