### ISSUE TITLE
PyTorch Support

### ISSUE THREAD

**Issue by jarednielsen** [tensorflow/lucid#138]
Is there PyTorch support for Lucid, or a similar library anyone could recommend?

**Comment by ludwigschubert** [comment]
I'm afraid there isn't any support for Pytorch. All the concepts should transfer, though, if you plan to build it!

I do know of https://github.com/sunalbert/lucid.pytorch, but I'm unsure what state this project is in. It does link to a bunch of projects in the readme, though I can't vouch for any of them. If you find one you'd recommend, please comment here and we may add it to our Readme.

**Comment by colah** [comment]
One thing to note is that you may be able to convert your trained PyTorch model to TensorFlow using one of the model conversion libraries. If you do that, you could use lucid to visualize it. :)

**Comment by jarednielsen** [comment]
Thanks, model conversion definitely seems like the route to go!

**Comment by krishvishal** [comment]
Did the model conversion route work ?

**Comment by andrewschreiber** [comment]
OpenAI announced a move to pytorch: https://openai.com/blog/openai-pytorch.

Any change of plans here?

**Comment by colah** [comment]
Not presently for Lucid. PyTorch has several interpretability projects already who we've been talking to and sharing some of our (not very mature) PyTorch code with. [Captum](https://captum.ai/) seems to have dedicated engineers working on user-ready infrastructure.

These projects are much better positioned than the lucid maintainers for maintaining a pytorch interpretability library. I'm hopeful  they'll support many of the same features eventually.

**Comment by greentfrapp** [comment]
Since this is a top hit when Googling "lucid pytorch", just wanted to spread the word about the [Lucent](https://github.com/greentfrapp/lucent) library! Essentially Lucid for PyTorch and works with torchvision.models. Check out the Colab notebooks at Lucent that reproduces the results from Lucid!
