### ISSUE TITLE
Larger input size

### ISSUE THREAD

**Issue by R-McHenry** [tensorflow/lucid#148]
Hi, I've been using lucid for artistic uses as it's exceptionally straightforward to incorporate losses based on deep representations. A big limitation so far is input resolution however. I understand that all the models in the model zoo require a fixed size input, but because I am only using some of the first several layers I know it is possible to cut off the rest of the layers and use a fully constitutional net instead, which would have no restriction on input shape beyond memory and channels.

I would be interested in any suggestions for how to go about doing this, like if I should try modifying the graph after loading a model, or maybe rebuild it elsewhere and import through the lucid model zoo new model workflow.

Also another option might be to try and bring in a new vision model that is fully constitutional, such as a semantic segmentation network.

**Comment by colah** [comment]
You can definitely do this. Lucid will happily ignore the input size if your objective is on conv layers, unless something about your model (eg. hard coded reshapes) makes this impossible. :)

```py
model = models.InceptionV1()
model.load_graphdef()

param_f = lambda: param.image(512, fft=True, decorrelate=True)
_ = render.render_vis(model, "mixed4a_pre_relu:2", param_f)
```

![image](https://user-images.githubusercontent.com/61658/53703059-6ccf8580-3dc2-11e9-94ee-5acc5cbecd8e.png)

It's slightly more complicated, but you can also work around memory constraints by doing random sampling of patches to optimize:

```py
with tf.Graph().as_default() as graph, tf.Session() as sess:
  
  t_img = param.image(512)
  crop_W = 128
  t_offset = tf.random.uniform((2,), 0, 512 - crop_W, dtype="int32")
  t_img_crop = t_img[:, t_offset[0]:t_offset[0]+crop_W, t_offset[1]:t_offset[1]+crop_W]
  T = render.make_vis_T(model, "mixed4a_pre_relu:2", t_img_crop)
  tf.initialize_all_variables().run()

  for i in range(512):
    T("vis_op").run()
    
  show(t_img.eval()[0])
```

![image](https://user-images.githubusercontent.com/61658/53703074-9c7e8d80-3dc2-11e9-90ea-8c4ef00e9c8d.png)

**Comment by colah** [comment]
One last trick to note: for artistic purposes, it can be helpful to use transforms to create sub-pixel resolution.

Here's an example:

```py
with tf.Graph().as_default() as graph, tf.Session() as sess:
  
  t_img = param.image(512)
  crop_W = 256
  t_offset = tf.random.uniform((2,), 0, 512 - crop_W, dtype="int32")
  t_img_crop = t_img[:, t_offset[0]:t_offset[0]+crop_W, t_offset[1]:t_offset[1]+crop_W]
  
  transforms=[transform.jitter(2), 
              transform.random_scale([0.3 + n/10. for n in range(20)]),
              transform.random_rotate(range(-10,11)),
              transform.jitter(2)]
  
  T = render.make_vis_T(model, "mixed4a_pre_relu:2", t_img_crop, 
                        transforms=transforms)
  tf.initialize_all_variables().run()

  for i in range(1024):
    T("vis_op").run()
    
  show(t_img.eval()[0])
```

![image](https://user-images.githubusercontent.com/61658/53703187-c5ebe900-3dc3-11e9-97fd-c11c4a92e520.png)

The line to pay attention to is:

```py
           transform.random_scale([0.3 + n/10. for n in range(20)]),
```

This causes images to be randomly scale by a factor of 0.3-0.5 before being fed into the network. As a result, pixels in the image are smaller than the pixels the network sees, but because they are randomly presented to the network in different combinations they still form nice structures. This can help create finer details structure in your art.

**Comment by R-McHenry** [comment]
Awesome, I actually just realized that it already works and I think the error I was running into was my own tensors having mismatched sizes. Coming back, I'm pleasantly surprised at all these tips and options, Thanks!
