### ISSUE TITLE
making Activation Atlas using custom model

### ISSUE THREAD

**Issue by timost1234** [tensorflow/lucid#156]
I was trying to make my own activation atlas using custom model. To define my `class InceptionV1(Model):` and `InceptionV1.layers`, I traced the source code to `lucid/lucid/modelzoo/aligned_activations.py` and found out that I didn't have the .npy file which stores the activations. Is there any tutorial to produce the activation .npy file. Thanks a lot!

**Comment by colah** [comment]
Yep! See this [colab notebook](https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/activation-atlas/activation-atlas-collect.ipynb).

Unfortunately, due to license restrictions on ImageNet, you need to create an account and download it yourself. Then you just run your model over it and sample activations, as in the notebook.

**Comment by dangkunal** [comment]
I tried recreating the results of colab notebook on Flowers dataset not Imagenet, To collect activation as .npy file I tried running this code

`def save_data(base_dir, options, activations, attributions):

  # spatial activations
  activations_path = optionsToURL(base_dir + "activations", "npy", options)
  with gfile.GFile(activations_path, "w") as f:
    np.save(f, activations)

  # spatial attributions to final classes
  attributions_path = optionsToURL(base_dir + "attribution", "npy", options)
  with gfile.GFile(attributions_path, "w") as f:
    np.save(f, attributions)`

But i am getting the error NameError: name 'optionsToURL' is not defined.

Kindly advise

**Comment by virilo** [comment]
I think you could use: (not tested yet)

	import os
	def optionsToURL(base_dir, extension, options):
	    filename=f"{options['split']}_{options['page']}.{extension}"
	    p=os.path.join(base_dir, filename)
	    #print(p)
	    return p

BTW: please, contact me if you was able to create an Activation Atlase with your own dataset
