### ISSUE TITLE
Error load_graphdef() when using InceptionV1 model

### ISSUE THREAD

**Issue by johnbisognano** [tensorflow/lucid#173]
model.load_graphdef() throws an error only when using InceptionV1 model. It affects running of the tutorial notebooks. Using a different model doesn't seem to throw an error.

<img width="1318" alt="Screen Shot 2019-06-02 at 10 23 56 PM" src="https://user-images.githubusercontent.com/40046297/58772036-3e11a880-8585-11e9-991b-9f44d5b5a9a0.png">

**Comment by ludwigschubert** [comment]
Sorry, can not reproduce—I imagine you're most likely running a notebook with an earlier version of lucid. Could you point me to the code in which you run into this issue?

**Comment by johnbisognano** [comment]
I'm no longer getting the issue either. I reported it since it came after a graphdef version update in tensorflow but it looks like it was updated again in tensorflow 9h ago.
