### ISSUE TITLE
type annotations

### ISSUE THREAD

**Issue by marlonjan** [tensorflow/lucid#183]
Hi!

Would you accept PRs with [PEP 484](https://www.python.org/dev/peps/pep-0484/) type annotations? It would make the codebase much easier to understand and simplify navigation through the code with an IDE (jump to type definitions, see usages, for example).

Since I'm currently getting familiar with the codebase I could occasionally add a few annotations and make a PR.

Cheers,
Marlon

**Comment by ludwigschubert** [comment]
Hey @marlonjan , we definitely would! I also want to get lucid to be fully type-hint annotated in the medium-term—the biggest trouble to me is that I immediately want to refactor code when the type hints start looking ugly. :D But please feel free to go ahead and submit PRs even for partial type hints! Thanks!
