### ISSUE TITLE
illustration2vec model support

### ISSUE THREAD

**Issue by huaji0353** [tensorflow/lucid#192]
https://github.com/rezoo/illustration2vec

**Comment by colah** [comment]
Hello! You will need to convert this model from caffe to TensorFlow and then import it as a lucid model.

**Comment by huaji0353** [comment]
thanks your reply！i had convert model caffe to tensorflow . And now how i import to lucid ?

**Comment by huaji0353** [comment]
> Hello! You will need to convert this model from caffe to TensorFlow and then import it as a lucid model.

thanks your reply！i had convert model caffe to tensorflow . And now how i import to lucid ?
