### ISSUE TITLE
Link to Slack invitation no longer work

### ISSUE THREAD

**Issue by heytitle** [tensorflow/lucid#195]
Hi, 

I tried to join  your `#proj-lucid` but the invitation link is no longer valid.

Could you please update the link?
or should I send you an email for the invitation?

**Comment by ludwigschubert** [comment]
We’ve added an indirection: http://slack.distill.pub and will attempt to keep that link up to date. (Who knew slack invites expire?)

**Comment by ludwigschubert** [comment]
(Please let me know if you still find the old link anywhere!)

**Comment by MasterScrat** [comment]
This link seems to have expired as well @ludwigschubert?

**Comment by Bathsheba** [comment]
Yes, all available links to the distill slack have expired.  Help?
Thanks.

**Comment by colah** [comment]
Updated the link.

**Comment by Bathsheba** [comment]
tyvm

**Comment by vkk800** [comment]
The link seems to be dead again. According to [this random guide](https://getlowdown.com/how-to-create-a-slack-community-and-landing-page-in-one-hour/) (Step 3, "Get your invite link"), it's also possible to create invite links that never expire.

**Comment by ludwigschubert** [comment]
@vkk800 thanks for the guide! I created a non-expiring invite and changed the [slack.distill.pub](http://slack.distill.pub) redirect.
