### ISSUE TITLE
Lucid: Python version?

### ISSUE THREAD

**Issue by riaz** [tensorflow/lucid#208]
Some of the notebook examples and  source code of lucid are targeting python2 not 3.

I installed lucid by running:
!pip install --quiet lucid==0.3

For example: caricature.py  (adding ranges wont work directly in python3 as they are not lists )
feature_inversion(img, model, layer, n_steps, cossim_pow)
     48       transform.jitter(8),
     49       transform.random_scale([0.9, 0.95, 1.05, 1.1] + [1]*4),
---> 50       transform.random_rotate(range(-5, 5) + [0]*5),
     51       transform.jitter(2),
     52     ]

Can someone help me with what am i supposed to do?

**Comment by ttumiel** [comment]
Lucid should work with both python 2 and 3 so you can use whichever you are more comfortable with. In python 3, just turn the range into a list: `list(range(-5,5))` and now the lists can be added together.

**Comment by riaz** [comment]
@ttumiel so i need to modify the source code then since caricature.py uses py2 type list

**Comment by ttumiel** [comment]
I can't find `transform.random_rotate(range(-5, 5) + [0]*5)` in the source - I see it only in the notebooks, in which case you could just edit the notebook interactively. Maybe previous versions of `caricature.py` contained it, in which case try using the latest version of lucid?

**Comment by riaz** [comment]
@ttumiel  got it. I had the v0.3 installed as mentioned in my original question. i was looking through its commit history and it had the line:
 Update caricature code 346a2f8 
so they have updated the code now, i am closing the tickets, i just had a older version
