### ISSUE TITLE
model.save() - Froze 0 variables. Converted 0 variables to const ops.

### ISSUE THREAD

**Issue by camoconnell** [tensorflow/lucid#215]
Hi there,

I'm working on saving a model out of the [style transfer example](https://research.google.com/seedbank/seed/style_transfer) on seedbank.

I have managed to generate a saved model by wrapping the  with the following code;

```
init_g = tf.global_variables_initializer()   
with tf.Session() as sess:

  sess.run(init_g)

  param_f = lambda: style_transfer_param(content_image, style_image)

  content_obj = 100 * activation_difference(content_layers, difference_to=CONTENT_INDEX)
  content_obj.description = "Content Loss"
    
  style_obj = activation_difference(style_layers, transform_f=gram_matrix, difference_to=STYLE_INDEX)
  style_obj.description = "Style Loss" 

  objective = - content_obj - style_obj 

  vis = render.render_vis(model, objective, param_f=param_f, thresholds=[40], verbose=False, print_objectives=[content_obj, style_obj])[-1]
   
  model.save(
    "saved_model.pb",
    input_name='Variable',
    image_shape=[224, 224, 3],
    output_names=['random_crop_1/Assert/Assert'],
    image_value_range=[-117, 138],
  )
```

however, judging by the logs below, it appears to be exporting an empty saved_model.pb

```
INFO:tensorflow:Froze 0 variables.
INFO:tensorflow:Converted 0 variables to const ops.
```

Should i be running sess.run() in the gram_matrix or activation_difference functions to populate the graph?

thanks

**Comment by colah** [comment]
Hm, I'm not sure that I'm following.

* It looks like you're trying to save the feature visualization graph rather than a model graph?
* It looks like you're calling `model.save` on an a model instance, rather than the abstract graph (ie. `Model.save`)? (That isn't an intended use of save and we should make it impossible.)
* I'm not sure what the goal of saving the model is, since it seems like you already have a working model instance?

Normally, you'd have a one script construct and export your model, then import it in another script for visualization.

**Comment by merri-ment** [comment]
Hi Colah,

Apologies, excuse the naive questions, i'm still getting familiar (conceptually) with how Style Transfer works.

The goal is to generate a saved_model.pb from the Style Transfer example and convert it via tensorflowjs_converter to the json web format, so i can run it in the browser. Therefore the flow is;
- Construct & Export model in python.
- Load & Run model in tfjs

To answer your first two points; 
In the example we create an instance of the InceptionV1 model and retrain it.
Having read the "Importing Models into Lucid" documentation on GH i had assumed that the code to retrain ( construct the model inference graph ) was, as per the snippet above;
```
param_f = lambda: style_transfer_param(content_image, style_image)
...
vis = render.render_vis(model, objective, param_f=param_f, thresholds=[40], verbose=False, print_objectives=[content_obj, style_obj])[-1]
```
Hence why i went about wrapping the code in a session and calling model.save() after render.render_vis().

**Comment by colah** [comment]
You might want to look at Interactive Stefan Sietzen and Manuela Waldner work on [Feature Visualization in the Browser](http://visxai.stefansietzen.at/).

Unfortunately, exporting a visualization graph like this isn't a supported use of lucid, and you're likely to run into a number of issues:

* `Model.save()` is intended to export models (ie. the object you call `model`) and not visualization graphs. You're likely to run into places where the code makes assumptions that don't hold for the visualization graph.
* The saved model is in a somewhat unusual format, with all weights burnt into the graph. We've never tested this for compatibility with tfjs.
* If you save the visualization graph, it will contain many ops that aren't typically in models. As a result, tfjs may not be able to run the graph.

I would recommend using tfjs to run your model, and implementing style transfer using Stefan's code or from scratch in javascript.

**Comment by camoconnell** [comment]
Thanks for taking the time to reply,

Ok, makes sense. 
The 'Feature Visualization in the Browser' link looks incredible. 

Will be in contact if i get an example running in tfjs using a Lucid trained model.
