### ISSUE TITLE
[Question] DeepDream without VGG ?

### ISSUE THREAD

**Issue by Uiuran** [tensorflow/lucid#226]
Hi all, it is indeed a question about Deep Dream, since i cant find a better place to put it (maybe you can indicate me ?), i will ask it here, after all Lucid is the heir of Deep Dream afaik. 

Is it possible to do the same you do with deep dream (i.e. objective maximization of hidden channels), without using VGG ?  I tried it with InceptionV4 but still without any success. 
Iam getting a lot of dimensionality errors in the gradients, but when i try with VGG it works fine, so the bug is not in the code ... Any example on how it is possible to work ? 
Thanks.

**Comment by colah** [comment]
DeepDream works fine with inception -- just take the tutorial notebook on the front page and use `objectives.deepdream("mixed4d")`.

Unfortunately, we're unable to help you debug your own implementation.

**Comment by Uiuran** [comment]
Yes i know that, but my question is, there is a reason why it should not
work for networks like InceptionV4_slim ? (for example)
My implementation is the same as:
https://github.com/tensorflow/examples/blob/master/community/en/r1/deepdream.ipynb

In other words, what is the criteria to choose networks such that we dont
find dimensionality problems ? there is an easy way to find it ? thank you
again, sorry for the insistence if it is not convenient for you.

**Comment by ludwigschubert** [comment]
> Iam getting a lot of dimensionality errors in the gradients, but when i try with VGG it works fine, so the bug is not in the code ... 
This means there _is_ a bug in the code. Here's a notebook doing what Chris suggested, to show that the issue is not with the `InceptionV4_slim` architecture or this implementation of the Deepdream objective: https://colab.research.google.com/drive/1F4HWENBaZ3D5Bw2Fh9g5klwDlK3GVzgG

If debugging the dimensionality errors you encounter doesn't work out, you might find it helpful to follow the implementation in this repository as a starting point? (It's admittedly a bit more "distributed" and complex than the notebook you linked.)

**Comment by Uiuran** [comment]
@ludwigschubert is i can realize Colah implementation, and with time grasp it, since i have a little (but enough) of software engineering. But i realize one point of this simple implementation gave as example:

You can only use Conv2D hidden channels (seems pretty obvious, but i dont see why not use ANY hidden channel to produce results, such a sequential hidden channels from say RNN or use Variational Hidden channels from VAE). 

If you use diverse Conv2D in the same objective, to maximize very diverse coarse grained features, this implementation also Bugs. 

I would like to stick with Chris Colah's implementation, but i will need time to Hack it, since i wanna put virtually any model in place to do more pervasive Image Edition, rather than the mere demonstrative lisergical deep dream (its quite fine, but we can do better, isnt that the purpose of lucid ?). 

Thank you again, i appreciate your attention very much.
