### ISSUE TITLE
Google colab switching to default use of Tensorflow 2 on March 27th 2020

### ISSUE THREAD

**Issue by Jorbay** [tensorflow/lucid#234]
Currently, I believe most notebooks in this project use Tensorflow 1 by default. According to [this notebook](https://colab.research.google.com/notebooks/tensorflow_version.ipynb#scrollTo=N2y2uqx9GfA5) (I have not yet found a more static source) states that Google Colab will switch to the default use of Tensorflow 2 by this Friday, March 27th 2020. 

Thus, because I believe all notebooks in this project do not declare the Tensorflow version explicitly, the notebooks will have to be updated to specify Tensorflow 1 to avoid making possibly broken calls in Tensorflow 2. Instructions for using Tensorflow 1 are given [here](https://colab.research.google.com/notebooks/tensorflow_version.ipynb#scrollTo=N2y2uqx9GfA5). 

This is expected to be an easy, one-line fix in each notebook. I'm unfamiliar with any more scalable solutions, but one may exist.

**Comment by abhinavsp0730** [comment]
Thanks for your concern. Some of the notebooks are now fixed, and rest of will also going to be fixed after merging
https://github.com/tensorflow/lucid/pull/245 this PR.
Thank you, kindly consider to close this issue.
