### ISSUE TITLE
[GSOC 2020] Query about internal development. 

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/lucid#237]
Hey, @colah I'm taking part in this year GSOC. And I found Tensorflow Lucif very interesting. But it's now only supports tensorflow 1.x, So is there any internal development planned for making it support tensorflow 2.x. If so I will draft a proposal in making all the notebook available to TensorFlow 2.x
Else kindly provide some Idea because I'm really intrested in Tensorflow Lucid.

**Comment by colah** [comment]
Hello! Just to clarify, I'm no longer at Google, although I continue to help maintain lucid. I also don't have any additional mentorship  bandwidth.

There's been some discussion on the Distill slack, but I think the lucid maintainers are presently leaning towards not porting lucid at this time. Many of us are still using  TF 1, and don't want tot ake on responsibility for maintaining lucid for a second TF version.

**Comment by abhinavsp0730** [comment]
Okay, thank you for responding.
