### ISSUE TITLE
Notebooks missing resources from storage.googleapis

### ISSUE THREAD

**Issue by tiedbranches** [tensorflow/lucid#252]
Hi,
I've been using the Semantic Dictionaries notebook for the past couple of weeks (adding these two lines at the beginning though:
`%tensorflow_version 1.x
assert tf.__version__.startswith('1')`
) with no issues.
It has been broken since yesterday though. I suspect that the problem is that the GoogLeNet spritemaps are unavailable. When I try to manually access the links to these spritemaps or the sample images (both stored in storage.googleapis) I either get a 
_"InvalidURI. Couldn't parse the specified URI. Illegal URI."_
or a
_"Access denied. There is an account problem for the requested project."_

The Readme.md on Github also seems broken, with images missing etc. (on every browser and computer I try).

Does anybody know what's going on? If it won't/can't be resolved, could I find those spritemaps anywhere else?

Thanks so much.

<img width="746" alt="Screenshot 2020-06-11 at 11 54 37" src="https://user-images.githubusercontent.com/56431987/84372237-1bc05b00-abdb-11ea-9b9c-d0493cdd54e3.png">
<img width="786" alt="Screenshot 2020-06-11 at 11 54 28" src="https://user-images.githubusercontent.com/56431987/84372263-24b12c80-abdb-11ea-9c1f-7a0681aca8e0.png">
<img width="1022" alt="Screenshot 2020-06-11 at 11 55 07" src="https://user-images.githubusercontent.com/56431987/84372287-2d096780-abdb-11ea-9873-d4d255727ba8.png">

**Comment by colah** [comment]
Thanks for reaching out! This data was hosted in a google cloud bucket I created when publishing the paper while at google and seems to have bene taken down. We're looking into it!

**Comment by tiedbranches** [comment]
Thanks so much for looking into it Chris! Lucid and this notebook in particular have proven invaluable for my project and I really hope I can keep using it! Godspeed.

**Comment by tiedbranches** [comment]
Resolved! Thanks so much.
