### ISSUE TITLE
Add "%tensorflow_version 1.x" to all Lucid notebooks

### ISSUE THREAD

**Issue by hav4ik** [tensorflow/lucid#256]
A lot of [distill.pub](https://distill.pub/) notebooks are referring to Lucid notebooks on Google Colab, which uses Tensorflow 2. A quick solution is to add `%tensorflow_version 1.x` workbook magic before importing tensorflow.

**Comment by ludwigschubert** [comment]
That's correct! There's an open WIP PR, but either way I'll ensure this line gets added to all notebooks soon. (he said on 2021-03-12)
