### ISSUE TITLE
Broken link to paper in source

### ISSUE THREAD

**Issue by vsiegel** [tensorflow/lucid#265]
In line 41 of
lucid/modelzoo/other_models/InceptionV1.py
a comment refers to the paper that originally defined the model,
but uses a broken link:

"This is a (re?)implementation of InceptionV1
 https://www.cs.unc.edu/~wliu/papers/GoogLeNet.pdf"

I suspect the content of it is this paper:
https://arxiv.org/pdf/1409.4842
but the filename is different "1409.4842.pdf"

**Comment by ludwigschubert** [comment]
Hi @vsiegel , thanks for pointing this out. The link is still valid as of today (2021-03-12), so I'll close for now. If you're still encountering this issue (link not accessible) I'd be happy to add the archive link, too.

**Comment by vsiegel** [comment]
Thanks - I can access it now. I suppose there was a transient problem when I reported it.
I did not document how the link was broken, but I think the domain must have been reachable.
I think it was something like that the home directory "~wliu" was not mounted or similar - and temporary.

**Comment by ludwigschubert** [comment]
Gotcha, @vsiegel . Just in case I've added additional links in d1144d0b201f75d6f3476e6851e8fd2f9908a4c2 :-)
