### ISSUE TITLE
save show(VIS) to .jpeg

### ISSUE THREAD

**Issue by 400lbhacker** [tensorflow/lucid#293]
I did get this working awhile ago, where I was able to write show(VIS) directly to an image file(.jpeg) . but I lost my source code.
I rerember trying with PIL and CV2 but dont rerember which one is the one that did end up working.

for example by default the examples simply display the output once finished, but does not save it to a file.
#-------
 vis = render.render_vis(model, objective, param_f=param_f, thresholds=[512], verbose=False, print_objectives=[content_obj, style_obj])[-1]

show(vis)
#------

I want to modify the above to also save vis to physical img. But the array format is tricky

**Comment by colah** [comment]
You want to use `lucid.misc.io.save`
