### ISSUE TITLE
Feature request: blur transform

### ISSUE THREAD

**Issue by Quasimondo** [tensorflow/lucid#39]
Not sure if this really makes sense, but a blur transform could be an interesting addition for lucid.optvis.transform - maybe it would allow to influence the behaviour of the high frequency patterns and/or the general scale of features.

**Comment by ludwigschubert** [comment]
Have you checked if the blur objectives—[`blur_input_each_step`, `blur_alpha_each_step`](https://github.com/tensorflow/lucid/blob/master/lucid/optvis/objectives.py#L247)—help achieve what you're looking for?

**Comment by Quasimondo** [comment]
Oh, I had not spotted those yet. Thanks for the tip, I will try that.

**Comment by ludwigschubert** [comment]
Sure!
