### ISSUE TITLE
Loading other models 

### ISSUE THREAD

**Issue by JegZheng** [tensorflow/lucid#40]
Hi, thanks for provding the powerful visualization. I just wonder can we also apply lucid on other models such as VAE or GAN? If not, is there any possible alternative method to ahieve this goal? Thanks.

**Comment by ludwigschubert** [comment]
Lucid performs activation maximization, so you should be able to create a visualization of any part of a differentiable model which produces a gradient with respect to an input image. 
We will have instructions for applying it to classification models other than GoogLeNet soon.

Closing as duplicate of #34
