### ISSUE TITLE
Examples in optvis readme don't work

### ISSUE THREAD

**Issue by Quasimondo** [tensorflow/lucid#42]
Maybe the documentation is outdated, but it looks like several of the examples are using methods that do not seem to be implemented:
https://github.com/tensorflow/lucid/tree/master/lucid/optvis

e.g.
```
obj = objectives.channel("mixed4a_pre_relu", 2)
param_f = lambda: tf.concat([
    param.rgb_sigmoid(param.naive([1, 128, 128, 3])),
    param.fancy_colors(param.naive([1, 128, 128, 8])/1.3),
    param.rgb_sigmoid(param.laplacian_pyramid([1, 128, 128, 3])/2.),
    param.fancy_colors(param.laplacian_pyramid([1, 128, 128, 8])/2./1.3),
], 0)
render_vis(model, obj, param_f)
```

**Comment by lindaterlouw** [comment]
I have the same problem. Seems the rgb_sigmoid function is replaced by to_valid_rgb(t, sigmoid=True)? I may be wrong about this.

**Comment by ludwigschubert** [comment]
@colah updated the documentation in 75a0d88. Does that help? I'll close for now, but feel free to reopen if you notice we missed a spot.

@lindaterlouw that is correct! (Feel free to leave out the `sigmoid=True`, which is a default parameter.)

Sorry for the breaking API changes! We try to be careful, but right now the API has not yet fully stabilized.
