### ISSUE TITLE
Specific usage

### ISSUE THREAD

**Issue by smile-intoxication** [tensorflow/lucid#47]
After each iteration in model training, whether and how can I compare the iteration results in the form of images using Lucid ?

**Comment by ludwigschubert** [comment]
Hi @smile-intoxication, I'm afraid I'm not sure what specifically you are asking about.
Could you clarify your usecase for us? A code example of what you're trying to do would be helpful.

**Comment by ludwigschubert** [comment]
_closed due to inactivity, feel free to reopen with a more detailed description of what you are running into_
