### ISSUE TITLE
A wrong in ActivationGrid.ipynb And my solution

### ISSUE THREAD

**Issue by BIRlz** [tensorflow/lucid#48]
When I run this [demo](https://github.com/tensorflow/lucid/blob/master/notebooks/building-blocks/ActivationGrid.ipynb), I can't get the predicted picture </n>
![tim 20180402234351](https://user-images.githubusercontent.com/23417594/38203088-9513f1b0-36d0-11e8-9bcf-ce927f90963b.png)
, and when I open this demo in jupyter, there is another wrong that shows . </n>![tim 20180402234842](https://user-images.githubusercontent.com/23417594/38203048-6a37c8d6-36d0-11e8-919c-dc94166ac5c5.png)
So, to show the picture in Terminal, we can 
`import matplotlib.pyplot as plt` 
then:
![tim 20180402235157](https://user-images.githubusercontent.com/23417594/38203166-e0942862-36d0-11e8-96fc-d3253129f6fb.png)
Note the green line and add those three lines above the green one.
At this time, we obtain the demo:
![tim 20180402231145](https://user-images.githubusercontent.com/23417594/38203208-06caff42-36d1-11e8-9c52-38734c7fdde1.png)
I wish to pull a request to fix this bug which is not a bug..LOL

**Comment by ludwigschubert** [comment]
Hi @BIRlz, your errors look like the installation process under the "Install/Import heading" was not successful. See if you can ensure these two dependencies install correctly:

```
pip install --quiet lucid==0.0.5
npm install -g svelte-cli@2.2.0
```

I can't offer more help with setting up your environment, but you can always use the notebooks on Colab. (Where the environment will be the same we use to develop them.)

**Comment by BIRlz** [comment]
Thank you sir~
