### ISSUE TITLE
No meaningful Visualizations in InceptionV3

### ISSUE THREAD

**Issue by tschwabe** [tensorflow/lucid#61]
Hey,

I wanted to visualize a custom InceptionV3 that I trained, but there were no interpretable Visualizations.
Therefore, I visualized the Keras InceptionV3, trained on Imagenet. But also with this model, I could not find any good visualizations. The closest one is `mixed6/concat`. To reproduce my problem, i  created a Colab-Notebook: 

https://colab.research.google.com/drive/1oIEeHZWxyU3vsqFpaQG1rs4YjHyYzfa1

If anyone knows, what I am doing wrong, or what the problem is, it would be great !

**Comment by ludwigschubert** [comment]
Your result for conv2d looks roughly as expected to me. 

When and why some models have easily interpretable basis directions is an open research question. Luckily visualizing basis directions is not the only interpretability technique: for example, you could try out [feature inversion](https://arxiv.org/abs/1412.0035), or other techniques in [Building Blocks](https://distill.pub/2018/building-blocks).

**Comment by tschwabe** [comment]
Thank you!
It's good and bad to hear this at the same time. I aimed to get visualizations as good as the ones in the papers. But at least I know that im on the right track.

**Comment by arvind** [comment]
Hi @tschwabe, we've just added a new notebook for [feature inversion caricatures](https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/misc/feature_inversion_caricatures.ipynb) that you may find more helpful with InceptionV3. This technique is useful when the basis directions don't align well with human-understandable concepts.
