### ISSUE TITLE
LookupError: No gradient defined for operation 'import/dense_1/BiasAdd' (op type: Dequantize)

### ISSUE THREAD

**Issue by pallavi7naik** [tensorflow/lucid#62]
![screenshot from 2018-05-21 19-40-55](https://user-images.githubusercontent.com/39490600/40311948-056b03c0-5d2f-11e8-8456-2cd554a1ac7d.png)

Here the 'import/BiasAdd' does not have gradient. But 'import/BiasAdd/(BiasAdd) might have the gradient. While backprop, lucid is taking 'import/BiasAdd' and it returns the above 'No gradient' error. I have built a keras model ( in .h5) then converted it to (.pb). Now I am trying to get relevance for each channel of my CNN. But the gradient is not back propagating because of the error. Please help me in finding the relevance.

**Comment by ludwigschubert** [comment]
You're likely importing your model differently than lucid expects.

Can you share a colab notebook that reproduces that error?

**Comment by ludwigschubert** [comment]
I'll close this due to inactivity for now, but feel free to reopen when you have a reproduction! :-)
