### ISSUE TITLE
lucid.misc.io.reading.read doesn't have a mode argument

### ISSUE THREAD

**Issue by girving** [tensorflow/lucid#63]
The documentation says `read` has a mode argument that defaults to `'rb'`:

https://github.com/tensorflow/lucid/blob/master/lucid/misc/io/reading.py#L56

Unfortunately, there is no such `mode` argument.  The lack of mode is unfortunate, since I need to set it to `'r'` to get svelte to work in Python 3.

**Comment by girving** [comment]
The downside would be that setting `encoding=`utf-8'` would decode in Python 2 as well, and presumably what one wants is `str` in both cases.  The specific problematic read call is

https://github.com/tensorflow/lucid/blob/master/lucid/scratch/web/svelte.py#L56

**Comment by girving** [comment]
What I have in my local tree to fix this: https://github.com/girving/lucid/commit/9d45e639f47bd220b455f417f568b47e9d9e92f5.

**Comment by ludwigschubert** [comment]
`v0.2.0` adds the mode property to all `misc.io.reading` functions, which is tested, but I have no integration tests for the svelte stuff. If you update and find that this did not help, please reopen.

**Comment by girving** [comment]
@ludwigschubert Confirmed that lucid now works with no change.  Thanks!
