### ISSUE TITLE
Kit fox vs. tench

### ISSUE THREAD

**Issue by girving** [tensorflow/lucid#65]
Please close if there's a banal explanation for this, but I noticed that the `InceptionV1` labels do not match the labels according to the `tensorflow/models` ImageNet data preprocessing.

In lucid,

```
>>> model = models.InceptionV1()
>>> model.load_graphdef()
>>> model.labels[:10]
['dummy',
 'kit fox',
 'English setter',
 'Siberian husky',
 'Australian terrier',
 'English springer',
 'grey whale',
 'lesser panda',
 'Egyptian cat',
 'ibex']
```

In the download of ImageNet, I see

```
% head -n 10 <...>/imagenet-tfrecords/labels.txt 
0:background
1:tench, Tinca tinca
2:goldfish, Carassius auratus
3:great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias
4:tiger shark, Galeocerdo cuvieri
5:hammerhead, hammerhead shark
6:electric ray, crampfish, numbfish, torpedo
7:stingray
8:cock
9:hen
```

Is one of these the standard?

**Comment by girving** [comment]
For comparison:

![Kit fox](https://cdn.firespring.com/images/cee09132-8552-4918-91e7-b78e598c1bc4.jpg)
![Tench](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Tinca_tinca_Prague_Vltava_2.jpg/1200px-Tinca_tinca_Prague_Vltava_2.jpg)

**Comment by ludwigschubert** [comment]
> Is one of these the standard?
I'm not sure. The weights we use for `models.InceptionV1()` were trained in ~2014 on a precursor of tensorflow, so the authors may have used a different ordering. To the best of my knowledge the labels we provide are correct for this set of weights.

**Comment by girving** [comment]
I confirmed that `model.labels` make sense for the trained model, and wrote the bit of code to map from one label numbering to the other.  Inference looks sensible.  Thanks!
