### ISSUE TITLE
Dead Link to Image

### ISSUE THREAD

**Issue by SeanPedersen** [tensorflow/lucid#67]
In https://github.com/tensorflow/lucid/blob/master/notebooks/building-blocks/SemanticDictionary.ipynb there is a dead link in the section "Spritemaps" (https://storage.googleapis.com/lucid-static/building-blocks/sprite_mixed4d_channel.jpeg).

This is what I get instead of the actual image:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to lucid-static/building-blocks/sprite_mixed4d_channel.jpeg.
</Details>
</Error>
```

I would appreciate a working link. No biggy though.

**Comment by ludwigschubert** [comment]
@SeanPedersen thanks for the report!

Looks like we rearranged the bucket—I have made the bucket access public again and updated the notebook to point at the correct sprite in 2137cdb.

Test the link:

![Test the link.](https://storage.googleapis.com/lucid-static/building-blocks/googlenet_spritemaps/sprite_mixed4d_channel.jpeg)

**Comment by SeanPedersen** [comment]
Works like a charm!
