### ISSUE TITLE
model.show_graph()?

### ISSUE THREAD

**Issue by colah** [tensorflow/lucid#87]
It should be pretty easy to provide a TensorFlow graph viewer embedded in iPython. In fact, there's example code on [stackoverflow](https://stackoverflow.com/questions/38189119/simple-way-to-visualize-a-tensorflow-graph-in-jupyter).

We could make this convenient for people?

**Comment by ludwigschubert** [comment]
Didn't @znah use to do this in some of his notebooks? We may already have it, I'll go look for it.

**Comment by ludwigschubert** [comment]
The internal colab wrapper is not OS, but it uses a legacy [tensorboard plugin](https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/graph/tf_graph_app). I'll see if I can get it to execute. 

**Cons**:
Doesn't work out of the box.

**Pros**:
Wouldn't need to send the graphdef to the tensorboard.appspot.com server just to visualize a graph.

**Comment by colah** [comment]
Hehe. The stackoverflow example... actually comes from the original deepdream notebook @znah made. :P 

I was worried originally about licensing! (Of course, Alex released it under Apache!)

**Comment by ludwigschubert** [comment]
Ah, sorry, I had that conversation with Alex in a DM. One more datapoint to use channels instead for visibility! :D

**Comment by ludwigschubert** [comment]
Colab team said to go ahead and use hosted version as they're between maintainers.
