### ISSUE TITLE
How can I find a particular neuron?

### ISSUE THREAD

**Issue by lemairecarl** [tensorflow/lucid#88]
I find that the CPPN parametrization produces very beautiful images, and I would like to experiment with similar feature visualizations as in the Differentiable Parameterizations paper.

Did someone already do a reverse mapping, with which we can visually search for a beautiful feature and find its corresponding neuron identifier?

**Comment by colah** [comment]
Hi Carl!

The [feature visualization article](https://distill.pub/2017/feature-visualization/) has an [appendix](https://distill.pub/2017/feature-visualization/appendix/) with visualizations of every neuron in GoogLeNet.

Additionally, look at the notebooks for the diagrams you're interested in. They may list the neurons you want!

**Comment by lemairecarl** [comment]
That's exactly what I was looking for! -- just like pretty much everything you publish! ;)

**Comment by colah** [comment]
Ah, there's two different ways of enumerating neurons in GoogLeNet.

GoogLeNet has an architecture that branches into 4 parallel branches and then concatenates them together. `mixed4d_3x3_bottleneck` is one of the branches of `mixed4d`, but because it wasn't the first one concatenated, it's shifted over by some offset. The easiest thing is probably to skim through the neurons, unfortunately.

**Comment by colah** [comment]
You can also just use `mixed4d_3x3_bottleneck` to reference it:

![image](https://user-images.githubusercontent.com/61658/43488671-547bcb7a-94cf-11e8-81bf-318e08692522.png)

**Comment by lemairecarl** [comment]
Great, thanks!

Also, If I want to produce a high resolution image, should I change the size of the vis when fitting the CPPN, or should I first fit it, save the weights and then render a bigger image using the "Arbitrary resolution images" section of the colab?

It seems that changing the size argument to `image_cppn` takes longer to train... does this mean that the xy2rgb mapping is dependent on the size argument when training the function?

**Comment by colah** [comment]
Actually, I slightly misspoke. `mixed4d_3x3_bottleneck` is one of the branches of `mixed4d`, but goes through another layer before concatenating it in. So you'll need to access it the way shown in the previous layer.

![image](https://user-images.githubusercontent.com/61658/43489244-31a1abc2-94d1-11e8-8e4a-3ad405cdd0f5.png)

> It seems that changing the size argument to `image_cppn` takes longer to train... does this mean that the xy2rgb mapping is dependent on the size argument when training the function?

I'd guess the main thing that's goin on is:

* You need to run the entire conv net on a larger image
* You need to run the cppn more times to generate all the pixels (smaller effect)

Consider training the cppn with a small image size and then render it larger at the end.

**Comment by lemairecarl** [comment]
It works!

I have another request... would you mind sharing what are the objectives used for making this striking mosaic?

<img width="1155" alt="capture d ecran 2018-08-01 a 12 11 40" src="https://user-images.githubusercontent.com/13444373/43533991-3e29c5b0-9584-11e8-8011-880449a75707.png">

**Comment by lemairecarl** [comment]
More importantly, I find (almost) no relationship between the xy2rgb viz I produce and what I see in the "catalog".

For example, with this channel from the catalog:

<img width="984" alt="capture d ecran 2018-08-01 a 12 44 10" src="https://user-images.githubusercontent.com/13444373/43535802-ea64ad64-9588-11e8-8489-70f0bb8e65c6.png">

Invoking this objective using `mixed4c_3x3:26`, I consistently obtain a (very nice) pepper shape/texture:

<img width="223" alt="capture d ecran 2018-08-01 a 12 45 48" src="https://user-images.githubusercontent.com/13444373/43535845-002caa7a-9589-11e8-90f0-d891b0207c4b.png">

Is it just me, or this is not the same feature?

**Comment by ludwigschubert** [comment]
@lemairecarl 1/2 no particular objective; these were created independently and then cherry-picked for aesthetic appeal.

**Comment by lemairecarl** [comment]
Just tried changing the objective to `mixed4c_3x3_bottleneck:26` (adding `_bottleneck`), and now I see the relationship. We can clearly see dog eyes, snouts and fur:

<img width="223" alt="capture d ecran 2018-08-01 a 12 58 56" src="https://user-images.githubusercontent.com/13444373/43536544-d3de41b6-958a-11e8-936f-0a67a7a2b2bb.png">

But dog features are so common that it could just be chance. Either with or without `_bottleneck`, the visualizations do not correspond.

**Comment by ludwigschubert** [comment]
@lemairecarl 2/2 same issue as before, mixed4c_3x3:26 will have a different offset in mixed4c. @colah's diagram above explains it.

**Comment by ludwigschubert** [comment]
@lemairecarl in particular, I looked up that `mixed4c_1x1` has 128 channels. Thus, `mixed4c_3x3:26` corresponds to `mixed4c:` `26`+`128` = `mixed4c:154`. [Looks more like it, too](https://distill.pub/2017/feature-visualization/appendix/googlenet/4c.html#4c-154). :D

**Comment by lemairecarl** [comment]
Oh! I see! Thanks for the example. Now I fully understand! :)

**Comment by hendrycks** [comment]
> The feature visualization article has an appendix with visualizations of every neuron in InceptionV1 (also known as GoogLeNet).

Are there CPPN visualizations of every neuron available for a model like InceptionV1?
