### ISSUE TITLE
some questions about tutorials

### ISSUE THREAD

**Issue by JackeyWang777** [tensorflow/lucid#98]
when I run the code
`model = models.InceptionV1()`
`model.load_graphdef()`
I meet an error:

TimeoutError                              Traceback (most recent call last)
D:\Anaconda\lib\urllib\request.py in do_open(self, http_class, req, **http_conn_args)
   1317                 h.request(req.get_method(), req.selector, req.data, headers,
-> 1318                           encode_chunked=req.has_header('Transfer-encoding'))
   1319             except OSError as err: # timeout error

D:\Anaconda\lib\http\client.py in request(self, method, url, body, headers, encode_chunked)
   1238         """Send a complete request to the server."""
-> 1239         self._send_request(method, url, body, headers, encode_chunked)
   1240 

D:\Anaconda\lib\http\client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1284             body = _encode(body, 'body')
-> 1285         self.endheaders(body, encode_chunked=encode_chunked)
   1286 

D:\Anaconda\lib\http\client.py in endheaders(self, message_body, encode_chunked)
   1233             raise CannotSendHeader()
-> 1234         self._send_output(message_body, encode_chunked=encode_chunked)
   1235 

D:\Anaconda\lib\http\client.py in _send_output(self, message_body, encode_chunked)
   1025         del self._buffer[:]
-> 1026         self.send(msg)
   1027 

D:\Anaconda\lib\http\client.py in send(self, data)
    963             if self.auto_open:
--> 964                 self.connect()
    965             else:

D:\Anaconda\lib\http\client.py in connect(self)
   1391 
-> 1392             super().connect()
   1393 

D:\Anaconda\lib\http\client.py in connect(self)
    935         self.sock = self._create_connection(
--> 936             (self.host,self.port), self.timeout, self.source_address)
    937         self.sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)

D:\Anaconda\lib\socket.py in create_connection(address, timeout, source_address)
    721     if err is not None:
--> 722         raise err
    723     else:

D:\Anaconda\lib\socket.py in create_connection(address, timeout, source_address)
    712                 sock.bind(source_address)
--> 713             sock.connect(sa)
    714             return sock

TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
<ipython-input-7-3e3d78d66937> in <module>()
      2 
      3 model = models.InceptionV1()
----> 4 model.load_graphdef()

D:\Anaconda\lib\site-packages\lucid\modelzoo\vision_base.py in load_graphdef(self)
     36 
     37   def load_graphdef(self):
---> 38     self.graph_def = load_graphdef(self.model_path)
     39 
     40   def post_import(self, scope):

D:\Anaconda\lib\site-packages\lucid\modelzoo\util.py in load_graphdef(model_url, reset_device)
     34 def load_graphdef(model_url, reset_device=True):
     35   """Load GraphDef from a binary proto file."""
---> 36   graphdef_string = read(model_url)
     37   try:
     38     graph_def = tf.GraphDef.FromString(graphdef_string)

D:\Anaconda\lib\site-packages\lucid\misc\io\reading.py in read(url, encoding, cache, mode)
     62     All bytes form the specified resource, or a decoded string of those.
     63   """
---> 64   with read_handle(url, cache, mode=mode) as handle:
     65     data = handle.read()
     66 

D:\Anaconda\lib\contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

D:\Anaconda\lib\site-packages\lucid\misc\io\reading.py in read_handle(url, cache, mode)
    101 
    102   if cache:
--> 103     handle = _read_and_cache(url, mode=mode)
    104   else:
    105     if scheme in ('http', 'https'):

D:\Anaconda\lib\site-packages\lucid\misc\io\reading.py in _read_and_cache(url, mode)
    154   else:
    155     log.info("Caching URL '%s' locally at '%s'.", url, local_path)
--> 156     with write_handle(local_path, 'wb') as output, read_handle(url, cache=False, mode='rb') as input:
    157       for chunk in _file_chunk_iterator(input):
    158         output.write(chunk)

D:\Anaconda\lib\contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

D:\Anaconda\lib\site-packages\lucid\misc\io\reading.py in read_handle(url, cache, mode)
    106       handle = _handle_web_url(url, mode=mode)
    107     elif scheme == 'gs':
--> 108       handle = _handle_gcs_url(url, mode=mode)
    109     else:
    110       handle = _handle_gfile(url, mode=mode)

D:\Anaconda\lib\site-packages\lucid\misc\io\reading.py in _handle_gcs_url(url, mode)
    130   base_url = 'https://storage.googleapis.com/'
    131   url = urljoin(base_url, resource_name)
--> 132   return _handle_web_url(url, mode=mode)
    133 
    134 

D:\Anaconda\lib\site-packages\lucid\misc\io\reading.py in _handle_web_url(url, mode)
    122 
    123 def _handle_web_url(url, mode='r'):
--> 124   return request.urlopen(url)
    125 
    126 

D:\Anaconda\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    221     else:
    222         opener = _opener
--> 223     return opener.open(url, data, timeout)
    224 
    225 def install_opener(opener):

D:\Anaconda\lib\urllib\request.py in open(self, fullurl, data, timeout)
    524             req = meth(req)
    525 
--> 526         response = self._open(req, data)
    527 
    528         # post-process response

D:\Anaconda\lib\urllib\request.py in _open(self, req, data)
    542         protocol = req.type
    543         result = self._call_chain(self.handle_open, protocol, protocol +
--> 544                                   '_open', req)
    545         if result:
    546             return result

D:\Anaconda\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    502         for handler in handlers:
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:
    506                 return result

D:\Anaconda\lib\urllib\request.py in https_open(self, req)
   1359         def https_open(self, req):
   1360             return self.do_open(http.client.HTTPSConnection, req,
-> 1361                 context=self._context, check_hostname=self._check_hostname)
   1362 
   1363         https_request = AbstractHTTPHandler.do_request_

D:\Anaconda\lib\urllib\request.py in do_open(self, http_class, req, **http_conn_args)
   1318                           encode_chunked=req.has_header('Transfer-encoding'))
   1319             except OSError as err: # timeout error
-> 1320                 raise URLError(err)
   1321             r = h.getresponse()
   1322         except:

URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

so what can I do or where can I download ?

**Comment by hegman12** [comment]
It looks like the script is unable to connect to internet to download the model from GCP. The model is at 
`'gs://modelzoo/vision/slim_models/InceptionV1.pb'`
The easiest way is to check if your internet is working and your script is able to connect to internet. Check if you are behind proxy and update proxy accordingly. Alternatively, you can also download the model manually from above and update your model file [here](https://github.com/tensorflow/lucid/blob/master/lucid/modelzoo/slim_models/Inception.py) to point to local directory.
